name: morph
channels:
  - conda-forge
dependencies:
  - dask
  - dask-mpi
  - marimo
  - numpy
  - nbval
  - pip
  - plotly
  - matplotlib
  - seaborn
  - pytest
  - pytest-cov
  - pytest-mock
  - pre-commit
  - python-elf
  - pyyaml
  - rich
  - scipy
  - scikit-image
  - z5py
  - zensical
  - mkdocstrings-python
  - pip:
      - python-fcl
      - setuptools==65.7.0
      - trimesh[easy,recommend]
      - xdg
      - skeletor
      - zmesh
      - -e ./
