name: morph
channels:
  - conda-forge
dependencies:
  - cachetools
  - dask
  - nbval
  - numpy
  - python-elf
  - pip
  - plotly
  - pytest
  - pytest-cov
  - scikit-image
  - scipy
  - trimesh
  - z5py
  - pre-commit
  - pip:
      - python-fcl
      - setuptools==65.7.0
      - shelved_cache
      - xdg
      - skeletor
      - -e ./
