name:
    morph
channels:
    - conda-forge
dependencies:
    - pip
    - setuptools==65.7.0
    - scipy
    - scikit-image
    - python-elf
    - numpy
    - trimesh
    - pytest
    - pytest-cov
    - nbval
    - pip:
        - python-fcl
