name: morph
channels:
  - conda-forge
dependencies:
  - dask
  - marimo
  - numpy
  - nbval
  - pip
  - plotly
  - pytest
  - pytest-cov
  - pytest-mock
  - pre-commit
  - python-elf
  - rich
  - scipy
  - scikit-image
  - z5py
  - zmesh
  - pip:
      - python-fcl
      - setuptools==65.7.0
      - trimesh[easy,recommend]
      - xdg
      - skeletor
      - -e ./
