name:
    morph
channels:
    - conda-forge
dependencies:
    - pip
    - scipy
    - scikit-image
    - python-elf
    - numpy
    - trimesh
    - pytest
    - pytest-cov
    - nbval
    - plotly
    - nbformat
    - cachetools
    - pip:
        - python-fcl
        - setuptools==65.7.0
        - shelved_cache
        - xdg
