import pytest
import numpy as np
import pandas as pd
from organelle_morphology.statistics import Statistics

def test_statistics_get_dataframe_basic(project_with_sources):
    """Verify that we get a basic dataframe with default properties."""
    stats = Statistics(project_with_sources)
    df = stats.get_dataframe()
    
    assert isinstance(df, pd.DataFrame)
    assert not df.empty
    assert "ID" in df.columns
    # Default properties check
    assert "mesh_volume" in df.columns
    assert "sphericity" in df.columns
    
    # Check that ID is the first column
    assert df.columns[0] == "ID"

def test_statistics_sorting_and_filtering(project_with_sources):
    """Check that columns are sorted and ID filtering works."""
    stats = Statistics(project_with_sources)
    
    # Request properties in non-alphabetical order
    props = ["water_tight", "mesh_area", "mesh_volume"]
    df = stats.get_dataframe(ids="mito_0001", properties=props)
    
    assert df.shape[0] == 1
    assert df.iloc[0]["ID"] == "mito_0001"
    
    # Columns should be ['ID', 'mesh_area', 'mesh_volume', 'water_tight']
    expected_order = ["ID", "mesh_area", "mesh_volume", "water_tight"]
    assert list(df.columns) == expected_order

def test_statistics_summary_dataframe(project_with_sources):
    """Test the statistical summary logic, including boolean handling."""
    stats = Statistics(project_with_sources)
    
    # Ensure we have some variation in a boolean column for testing
    # (In synthetic data, water_tight is usually True)
    df_data = stats.get_dataframe(properties=["mesh_volume", "water_tight", "sphericity"])
    
    summary_df = stats.get_summary_dataframe(df_data)
    
    assert "Measure" in summary_df.columns
    assert "Average (or Share)" in summary_df["Measure"].values
    
    # Check Average row
    avg_row = summary_df[summary_df["Measure"] == "Average (or Share)"].iloc[0]
    
    # Volume should be a float
    assert isinstance(avg_row["mesh_volume"], float)
    
    # water_tight should be a float between 0 and 1 (the share)
    assert 0.0 <= avg_row["water_tight"] <= 1.0
    
    # Check that non-average measures are NaN/missing for booleans
    std_row = summary_df[summary_df["Measure"] == "Std Dev"].iloc[0]
    assert pd.isna(std_row["water_tight"])

def test_statistics_skeleton_guard(project_with_sources):
    """Verify that skeleton stats are handled gracefully when not yet computed."""
    stats = Statistics(project_with_sources)
    
    # We haven't called project.skeletonize_wavefront() in this test yet
    df = stats.get_dataframe(properties=["num_nodes", "mesh_volume"])
    
    assert "num_nodes" in df.columns
    # Should be all NaNs because skeletons don't exist
    assert df["num_nodes"].isna().all()

def test_statistics_empty_project(project):
    """Ensure it doesn't crash on a project with no sources."""
    stats = Statistics(project)
    df = stats.get_dataframe()
    assert df.empty
    
    summary = stats.get_summary_dataframe(df)
    assert summary.empty

def test_geometric_mean_handling():
    """Unit test for the geometric mean logic with zeros/positives."""
    # We don't need a full project for a quick logic check
    data = pd.DataFrame({
        "pos": [1, 10, 100],
        "with_zero": [0, 10, 20]
    })
    
    # Internal math check
    # Geometric mean of 1, 10, 100 is 10
    calc_gm = lambda x: np.exp(np.log(x[x > 0]).mean()) if np.any(x > 0) else np.nan
    
    assert np.isclose(calc_gm(data["pos"]), 10.0)
    # With zero, it should only consider the positive values (10, 20) -> ~14.14
    assert calc_gm(data["with_zero"]) > 10.0

def test_statistics_mcs_aggregation(project_with_sources, mocker):
    """Verify that MCS data is correctly pulled from the mcs_dict."""
    stats = Statistics(project_with_sources)
    
    # Pick one organelle to mock
    org = project_with_sources.get_organelles("mito_0001")[0]
    
    # Mock the mcs_dict property to return specific test values
    # In the real app, these are generated by MembraneContactSiteCalculator
    test_mcs_data = {
        "contact_er": 150.5,
        "contact_nucleus": 42.0
    }
    mocker.patch.object(type(org), 'mcs_dict', new_callable=mocker.PropertyMock, return_value=test_mcs_data)
    
    # Request the specific contact keys
    props = ["contact_er", "contact_nucleus", "mesh_volume"]
    df = stats.get_dataframe(ids="mito_0001", properties=props)
    
    # Verify the values were extracted correctly
    assert df.iloc[0]["contact_er"] == 150.5
    assert df.iloc[0]["contact_nucleus"] == 42.0
    
    # Verify that the summary also handles these new columns
    summary_df = stats.get_summary_dataframe(df)
    avg_row = summary_df[summary_df["Measure"] == "Average (or Share)"].iloc[0]
    assert avg_row["contact_er"] == 150.5