name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing on ${{matrix.os}} (Python ${{matrix.python-version}})
    runs-on: ${{matrix.os}}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.11", "3.13"]
        exclude:
          - os: windows-latest
            python-version: "3.11"
    if: ${{ github.event.pull_request == null || github.event.pull_request.draft != true }}
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'powershell' || 'bash -el {0}' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.3
        with:
          # setuptools_scm requires a non-shallow clone of the repository
          fetch-depth: 0

      - name: Add conda instance
        uses: conda-incubator/setup-miniconda@v4.0.1
        with:
          miniforge-version: latest
          mamba-version: "*"
          channels: local,conda-forge
          python-version: ${{matrix.python-version}}
          activate-environment: morph
          environment-file: environment-dev.yml
          conda-remove-defaults: true

      - name: Run Python tests
        run: |
          pytest --cov --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: always() && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: codecov/codecov-action@v7.0.0
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
